image: Visual Studio 2019

environment:
  # 'appveyor build2' token
  GITHUB_ACCESS_TOKEN:
    secure: f6XWOyfjFS+fTkPWNoR2GbqOhhbu6KTbQdz0o+0yozD1DRA0XIci5xNJDDTtFUu1
  # MyGet apikey
  CI_DEPLOYMENT_API_KEY:
    secure: EOVLFyiHRhh9Jij3/mITdSV5JH1SzT8JUbqqTIFtvOPndNeMme3mME01ws3+5nFB
  # NuGet.org apikey
  DEPLOYMENT_API_KEY:
    secure: sodorJrPlumQEGdwwRYZ9E/+5Me1KiEessgorKXYchcSIY12v9TEF49jm2oe0ATn

init:
  - git config --global core.autocrlf input

install:
  - dotnet --info
  # The last part will make CMD ignore any non-zero exit codes from 'dotnet --version'
  - dotnet --version & exit 0

build_script:
  - ps: .\build.ps1 -target AppVeyor -configuration Debug -verbosity diagnostic
  - ps: .\build.ps1 -target AppVeyor -configuration Release -verbosity diagnostic

test: off

deploy: off
