image: Visual Studio 2022

environment:
  # Needed for GitVersion to work better
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
  # 'appveyor build2' token
  GITHUB_ACCESS_TOKEN:
    secure: f6XWOyfjFS+fTkPWNoR2GbqOhhbu6KTbQdz0o+0yozD1DRA0XIci5xNJDDTtFUu1
  # MyGet apikey
  CI_DEPLOYMENT_API_KEY:
    secure: EOVLFyiHRhh9Jij3/mITdSV5JH1SzT8JUbqqTIFtvOPndNeMme3mME01ws3+5nFB
  # NuGet.org apikey
  DEPLOYMENT_API_KEY:
    secure: kiihplCA2tHVSB6tB1ryE/5aS0mSDevfQDjtWwRIrGqNWFOTMUXDZMI9UF3tJs8g
  # 'packages_pat_public' PAT (classic)
  GITHUB_TOKEN:
    secure: ESUR8UUfZGeT7sNRirn7b3q1TlUrivATlUpdIlpa2iuf86oKj47cBWPowG3nJP8w

init:
  - git config --global core.autocrlf true

install:
  - dotnet --info
  # The last part will make CMD ignore any non-zero exit codes from 'dotnet --version'
  - dotnet --version & exit 0

before_build:
  # GitHub does not yet support anonymous access to public NuGet repositories.
  - ps: dotnet nuget add source "https://nuget.pkg.github.com/maxild/index.json" --username maxild --password $env:GITHUB_TOKEN --store-password-in-clear-text --name github-maxild

build_script:
  - ps: .\build.ps1 -verbose -target AppVeyor -configuration Debug -verbosity diagnostic
  - ps: .\build.ps1 -verbose -target AppVeyor -configuration Release -verbosity diagnostic

test: off

deploy: off
