# See http://help.appveyor.com/discussions/questions/2449-what-os-setting-should-i-use-to-get-windows-machine-with-no-dotnet-cli-bits-installed
# os: Visual Studio 2013 # Image without preinstalled .NET Core SDK
# We use image with preinstalled .NET Core SDK, because we also need net452
os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

build_script:
  - ps: .\build.ps1 -target Verify -configuration Debug
  - ps: .\build.ps1 -target All -configuration Release

test: off

artifacts:
- path: artifacts\**\*.nupkg
  name: Packages

deploy:
# Deploy to Myget on every push to Github
- provider: NuGet
  server: https://www.myget.org/F/maxfire-ci/api/v2/package
  api_key:
    secure: EOVLFyiHRhh9Jij3/mITdSV5JH1SzT8JUbqqTIFtvOPndNeMme3mME01ws3+5nFB
  skip_symbols: true
  artifact: Packages
# Deploy to NuGet.org only on tagged master branch pushes to Github
- provider: NuGet
  api_key:
    secure: DInFdMch2u8btkaNWMOPYOsnV6eknvY0rJvdxIkCi3Sijxc+b6i8a7142SbWtzBK
  skip_symbols: true
  artifact: Packages
  on:
    branch: master
    appveyor_repo_tag: true # trigger deployment on tag only
